### ISSUE TITLE
bump ruby dependencies

### ISSUE THREAD

**Issue by ajb** [codeforamerica/git-jekyll-preview#4]
heyo,

are you guys still using this at CfA? it's super handy, but it seems like the ruby dependencies aren't up-to-date with what GitHub Pages has installed. the [`github-pages` gem](http://rubygems.org/gems/github-pages) seems to package things up nicely, if you just wanted to install from there.

**Comment by migurski** [comment]
Thanks! We are still using it, though not for GH-pages projects (mostly). Can you do a PR?

**Comment by ajb** [comment]
You tell me if that will work -- I'm not a chef user but it seemed like an easy fix. `rdiscount` is installed with `github-pages`, so it makes things a bit simpler, too.

To be honest, I can't believe this service hasn't received more attention. It solves a pretty big need for folks who use GitHub Pages for hosting.

**Comment by migurski** [comment]
Looks pretty legit! I’ll test it out and see how it does.

Thanks by the way; we're not promoting it particularly, but everyone in the office uses it for website work.

**Comment by migurski** [comment]
Handled in 9aaed862fd06d95d3b9bc32e9e98d09f69391fe3.
