### ISSUE TITLE
Looks to be unavailable?

### ISSUE THREAD

**Issue by ajb** [codeforamerica/git-jekyll-preview#6]
I can't seem to get this working at all since the last update. http://jekit.codeforamerica.org/codeforamerica/beyondtransparency times out, as well as the other (private) repos I've tried.

**Comment by migurski** [comment]
That’s weird—I’m looking at http://jekit.codeforamerica.org/codeforamerica/beyondtransparency/master/ right now? I can’t find any errors in the log.

**Comment by ajb** [comment]
Cleared cookies, revoked oauth token, still happening. Tried with another GitHub account (@dobthound) and I'm seeing the same, which is that the GET to https://jekit.codeforamerica.org/oauth/callback?code=XXXXXXXX&state=foobar is timing out.

**Comment by ajb** [comment]
Did something happen to the SSL cert, by chance?

**Comment by migurski** [comment]
Ah, that might be the thing. Thank you, not sure why I wasn't seeing this.

**Comment by migurski** [comment]
Added the SSL cert, try now?

**Comment by ajb** [comment]
It works, but redirects from https to http.

On Tue, Sep 30, 2014 at 5:11 PM, migurski notifications@github.com wrote:

> Added the SSL cert, try now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/git-jekyll-preview/issues/6#issuecomment-57383617
> .

## 

Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by migurski** [comment]
Ah yeah, it's always done that.

**Comment by ajb** [comment]
Gotcha. Thanks again for your work on this, glad we can start using it
again.

On Tue, Sep 30, 2014 at 8:24 PM, migurski notifications@github.com wrote:

> Ah yeah, it's always done that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/git-jekyll-preview/issues/6#issuecomment-57403236
> .

## 

Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by migurski** [comment]
Yeah, hugely relieved to get your github-pages stuff going; it all seems a bit snappier now.

Re: SSL, do you think it's a requirement?

**Comment by ajb** [comment]
Yes, I do, since Jekit stores a session that gives access to contents of
private repos. CFA's gotta have a wildcard cert, too?

On Tue, Sep 30, 2014 at 8:35 PM, migurski notifications@github.com wrote:

> Yeah, hugely relieved to get your github-pages stuff going; it all seems a
> bit snappier now.
> 
> Re: SSL, do you think it's a requirement?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/git-jekyll-preview/issues/6#issuecomment-57404056
> .

## 

Adam Becker
510.928.9111
@AdamJacobBecker

**Comment by migurski** [comment]
Not yet, since our SSL needs have been somewhat narrow so far. I have one for jekit obviously, might expand that to the site as a whole.
