### ISSUE TITLE
Anyway to make this also work with Flask's Jinja templates?

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/git-jekyll-preview#9]
The communities team wants [an easy way](https://github.com/codeforamerica/brigade-alpha/issues/81) to preview their changes to the Brigade site.

Trouble is I need some server side smarts for the Brigade site. What is possible?

**Comment by ondrae** [comment]
I could perhaps have the /tools section of the Brigade site, where the communities team will be doing most of their work, be a separate GitHub Pages repo?

**Comment by migurski** [comment]
I don't think it’d be compatible with Jekyll’s templating language; they’re similar but slightly different. I’ll close this but comment over there.
